/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.QR.main;

import com.QR.form.Form1;
import com.QR.form.printLabel;
import com.QR.form.productAdd;
import com.QR.form.productRemove;
import com.QR.form.reports;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.raven.menu.EventMenu;
import com.raven.menu.MainForm;
import com.raven.menu.MenuItem;
import java.awt.Component;
import java.awt.EventQueue;

/**
 *
 * @author Arca
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    
    
    public main() {
        initComponents();
        menu.setSelectedIndex(0);
        menu.addEventMenuSelected(new EventMenu() {
            @Override
            public void mainMenuSelected(MainForm mainForm, int index, MenuItem menuItem) {
                // Implementation for handling main menu selection
                Form1 form = new Form1();
                mainForm.displayForm(form);
            }

            @Override
            public void subMenuSelected(MainForm mainForm, int index, int subMenuIndex, Component menuItem) {
                // Implementation for handling sub-menu selection

                // Create an instance of the productAdd form
                if(index == 0 && subMenuIndex == 0){
                    productAdd selectedForm = new productAdd();
                    mainForm.displayForm(selectedForm);
                }
                else if(index == 1 && subMenuIndex == 0){
                    productRemove selectedForm = new productRemove();
                    mainForm.displayForm(selectedForm);
                }
                else if(index == 2 && subMenuIndex == 0){
                    reports selectedForm = new reports();
                    mainForm.displayForm(selectedForm);
                }
                else if(index == 2 && subMenuIndex == 1){
                    printLabel selectedForm = new printLabel();
                    mainForm.displayForm(selectedForm);
                }
               
                

              

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new com.raven.menu.Menu();
        jLabel1 = new javax.swing.JLabel();
        menuItem1 = new com.raven.menu.MenuItem();
        menuItem2 = new com.raven.menu.MenuItem();
        menuItem3 = new com.raven.menu.MenuItem();
        subMenuPanel2 = new com.raven.menu.SubMenuPanel();
        mainForm = new com.raven.menu.MainForm();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuLightMode = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setMainForm(mainForm);
        menu.setSubMenuPanel(subMenuPanel2);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QR/img/Home.png"))); // NOI18N
        menu.add(jLabel1);

        menuItem1.setBackground(new java.awt.Color(51, 51, 255));
        menuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QR/img/Plus.png"))); // NOI18N
        menuItem1.setText("menuItem1");
        menuItem1.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "com/QR/img/PlusSub.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem1.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Ürün Ekle" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        menu.add(menuItem1);

        menuItem2.setBackground(new java.awt.Color(255, 0, 102));
        menuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QR/img/Close.png"))); // NOI18N
        menuItem2.setText("menuItem2");
        menuItem2.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "com/QR/img/CloseSubMenu.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem2.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Stok Çıkar" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem2ActionPerformed(evt);
            }
        });
        menu.add(menuItem2);

        menuItem3.setBackground(new java.awt.Color(153, 255, 153));
        menuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QR/img/Scroll.png"))); // NOI18N
        menuItem3.setText("menuItem3");
        menuItem3.setMenuIcon(new javax.swing.AbstractListModel() {
            String[] strings = { "com/QR/img/ReportsSubMenu.png", "com/QR/img/PrintSubMenu.png" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem3.setMenuModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Raporlar", "Etiket Çıkar" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem3ActionPerformed(evt);
            }
        });
        menu.add(menuItem3);

        jMenu1.setText("Dosya");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Düzenle");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Seçenekler");

        menuLightMode.setText("Aydınlık Mod");
        menuLightMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLightModeActionPerformed(evt);
            }
        });
        jMenu3.add(menuLightMode);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(subMenuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
            .addComponent(subMenuPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        
    }//GEN-LAST:event_menuItem1ActionPerformed

    private void menuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem2ActionPerformed

    private void menuLightModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLightModeActionPerformed
        if (menuLightMode.isSelected()) {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatIntelliJLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        } else {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatDarculaLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }//GEN-LAST:event_menuLightModeActionPerformed

    private void menuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarculaLaf.setup();
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private com.raven.menu.MainForm mainForm;
    private com.raven.menu.Menu menu;
    private com.raven.menu.MenuItem menuItem1;
    private com.raven.menu.MenuItem menuItem2;
    private com.raven.menu.MenuItem menuItem3;
    private javax.swing.JCheckBoxMenuItem menuLightMode;
    private com.raven.menu.SubMenuPanel subMenuPanel2;
    // End of variables declaration//GEN-END:variables
}
