/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.QR.form;

import com.QR.helper.buttonActions;
import com.QR.helper.tableActions;
import javax.swing.JTable;

/**
 *
 * @author Arca
 */
public class productRemove extends javax.swing.JPanel {

    /**
     * Creates new form productRemove
     */
    
    
    public productRemove() {
        initComponents();
        
        tableActions tableAction = new tableActions();
        tableAction.tb_load(removeProductTable);
        tableAction.tb_loadFinal(removeProductTableFinal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p_barcode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        removeProductTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        p_musteri = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        removeProductTableFinal = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Barcode:");

        p_barcode.setText("0");
        p_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_barcodeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QR/img/Cancel.png"))); // NOI18N
        jButton1.setText("Stok Çık");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        removeProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Çıkıldı", "Barcode", "Kategori", "Materyal", "Kalınlık", "Uzunluk", "Kilogram", "Renk", "Üretim Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        removeProductTable.getTableHeader().setReorderingAllowed(false);
        removeProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(removeProductTable);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Müşteri:");

        p_musteri.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        p_musteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_musteriActionPerformed(evt);
            }
        });

        removeProductTableFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Barcode", "Kategori", "Materyal", "Kalınlık", "Uzunluk", "Kilogram", "Renk", "Üretim Tarihi", "Müşteri", "Çıkış Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        removeProductTableFinal.setToolTipText("");
        removeProductTableFinal.getTableHeader().setReorderingAllowed(false);
        removeProductTableFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeProductTableFinalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(removeProductTableFinal);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QR/img/Search.png"))); // NOI18N
        jButton2.setText("Bul");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QR/img/Cancel.png"))); // NOI18N
        jButton3.setText("Çıkış İptal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_musteri, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_musteri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        String barcode = p_barcode.getText();
        String musteri = p_musteri.getText();
        
        buttonActions buttonAction = new buttonActions();
        buttonAction.sellAction(barcode, musteri);
        
        tableActions tableAction = new tableActions();
        tableAction.tb_load(removeProductTable);
        tableAction.tb_loadFinal(removeProductTableFinal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void p_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_barcodeActionPerformed

    private void p_musteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_musteriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_musteriActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String search = p_barcode.getText();

        tableActions tableAction = new tableActions();
        tableAction.tbLineLoad(search, removeProductTable);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void removeProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeProductTableMouseClicked
        //gets barcode column from the clicked row
        JTable source = (JTable)evt.getSource();
        int column = 1;
        int row = source.rowAtPoint(evt.getPoint());

        if (row >= 0 && column >= 0 && column < source.getColumnCount()) {
            String value = source.getModel().getValueAt(row, column) + "";
            p_barcode.setText(value);
        }
    }//GEN-LAST:event_removeProductTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String search = p_barcode.getText();
        String musteri = p_musteri.getText();
        
        buttonActions buttonAction = new buttonActions();
        buttonAction.unSellAction(search, musteri);
        
        tableActions tableAction = new tableActions();
        tableAction.tb_load(removeProductTable);
        tableAction.tb_loadFinal(removeProductTableFinal);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void removeProductTableFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeProductTableFinalMouseClicked
        
        //gets musteri column from the clicked row
        
        JTable source = (JTable)evt.getSource();
        int column = 8;
        int row = source.rowAtPoint(evt.getPoint());

        if (row >= 0 && column >= 0 && column < source.getColumnCount()) {
            String value = source.getModel().getValueAt(row, column) + "";
            p_musteri.setText(value);
        }
    }//GEN-LAST:event_removeProductTableFinalMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField p_barcode;
    private javax.swing.JTextField p_musteri;
    private javax.swing.JTable removeProductTable;
    private javax.swing.JTable removeProductTableFinal;
    // End of variables declaration//GEN-END:variables
}
